
reactcom-elasticsearch:
  image: elasticsearch:5.2
  container_name: reactcom-elasticsearch

reactcom-webserver:
  image: phpdockerio/nginx:latest
  container_name: reactcom-webserver
  volumes:
      - ../src:/var/www/reactcom
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8059:80"
  links:
   - reactcom-php-fpm

reactcom-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: reactcom-php-fpm
  volumes:
    - ../src:/var/www/reactcom
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - reactcom-elasticsearch